# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-11-04 20:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='order',
        ),
    ]
