# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-11-04 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_project_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
