# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-11-08 04:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_project_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='skills',
        ),
    ]
