# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-11-10 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_skill_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('url', models.CharField(max_length=2000)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='demo',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='project',
            name='prototype',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
