# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-11-10 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20161110_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='links',
            field=models.ManyToManyField(to='myapp.Link'),
        ),
    ]
