# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-11-10 02:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_project_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='attr',
            field=models.CharField(default=datetime.datetime(2016, 11, 10, 2, 24, 59, 212882, tzinfo=utc), max_length=30),
            preserve_default=False,
        ),
    ]
