# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-11-11 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_auto_20161111_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='projects',
            field=models.ManyToManyField(blank=True, to='myapp.Project'),
        ),
        migrations.AlterField(
            model_name='course',
            name='skills',
            field=models.ManyToManyField(blank=True, to='myapp.Skill'),
        ),
    ]
