# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-11-15 00:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_experience_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='degree',
            new_name='job',
        ),
    ]
