# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-11-15 00:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_auto_20161115_0041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='minor',
        ),
    ]
