# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-11-15 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_remove_experience_minor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='institution',
            field=models.CharField(max_length=50),
        ),
    ]
