# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-11-16 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_auto_20161116_0333'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='degree',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
