# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-11-16 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_remove_education_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='degrees',
            field=models.ManyToManyField(blank=True, to='myapp.Degree'),
        ),
    ]
