# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-11-16 03:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_auto_20161116_0342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='abroad',
        ),
    ]
