# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-11-16 22:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_remove_education_abroad'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='major',
            field=models.BooleanField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
