# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-11-17 04:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0046_auto_20161117_0435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='level',
        ),
    ]
