# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-12-13 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0049_auto_20161117_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='volunteer',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
