# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-12-13 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0050_experience_volunteer'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='abroad',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
